language: rust
rust:
  - 1.2.0
  - beta
  - nightly
sudo: false
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
  - export TARGET=$ARCH-$OS
  - curl -sO https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - tar xf rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - rm -rf $HOME/rust/lib/rustlib/$TARGET
  - mv rust-$TRAVIS_RUST_VERSION-$TARGET/rustc/lib/rustlib/$TARGET $HOME/rust/lib/rustlib
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test --target $TARGET
  - cargo test --target $TARGET --manifest-path libc-test/Cargo.toml
  - cargo doc --no-deps
notifications:
  email:
    on_success: never

# Need gcc 4.7 for alignof/stdalign.h and we use multilib as we test both 32/64
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - gcc-4.7-multilib
env:
  - ARCH=x86_64 CC=gcc-4.7
  - ARCH=x86_64 CC=clang
  - ARCH=i686 CC=gcc-4.7
  - ARCH=i686 CC=clang

os:
  - linux
  - osx
