environment:
  global:
    MSYS2_BASEVER: 20150512
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_ARCH: x86_64
    MSYS2_BITS: 64
    MSYSTEM: MINGW64
  - TARGET: i686-pc-windows-gnu
    MSYS2_ARCH: i686
    MSYS2_BITS: 32
    MSYSTEM: MINGW32
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  - ps: ci\msys2.ps1
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;%CD%\msys2\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
  - cargo run --manifest-path libc-test/Cargo.toml

branches:
  only:
    - master
